### ISSUE TITLE
QL Query: UPDATE `coderity`.`pages` AS `Page` SET `Page`.`lft` = `Page`.`lft` + 2 WHERE `Page`.`lft` >= AND NOT (`Page`.`id` = 2)

### ISSUE THREAD

**Issue by flik** [coderity/app#11]
I was Adding new page and received this error.

Database Error
Error: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND NOT (`Page`.`id` = 2)' at line 1

SQL Query: UPDATE `coderity`.`pages` AS `Page` SET `Page`.`lft` = `Page`.`lft` + 2 WHERE `Page`.`lft` >= AND NOT (`Page`.`id` = 2)

Notice: If you want to customize this error message, create app/View/Errors/pdo_error.ctp

Stack Trace
CORE/Cake/Model/Datasource/DboSource.php line 460 → PDOStatement->execute(array)
CORE/Cake/Model/Datasource/DboSource.php line 426 → DboSource->_execute(string, array)
CORE/Cake/Model/Datasource/Database/Mysql.php line 415 → DboSource->execute(string)
CORE/Cake/Model/Model.php line 2654 → Mysql->update(Page, array, null, array)
CORE/Cake/Model/Behavior/TreeBehavior.php line 1159 → Model->updateAll(array, array)
CORE/Cake/Model/Behavior/TreeBehavior.php line 1147 → TreeBehavior->_sync(Page, integer, string, string, boolean, string)
CORE/Cake/Model/Behavior/TreeBehavior.php line 1048 → TreeBehavior->_sync(Page, integer, string, string, boolean)
CORE/Cake/Model/Behavior/TreeBehavior.php line 96 → TreeBehavior->_setParent(Page, string, boolean)
[internal function] → TreeBehavior->afterSave(Page, boolean, array)
CORE/Cake/Utility/ObjectCollection.php line 128 → call_user_func_array(array, array)
[internal function] → ObjectCollection->trigger(CakeEvent)
CORE/Cake/Event/CakeEventManager.php line 243 → call_user_func(array, CakeEvent)
CORE/Cake/Model/Model.php line 1953 → CakeEventManager->dispatch(CakeEvent)
CORE/Cake/Model/Model.php line 1747 → Model->_doSave(array, array)
APP/Controller/PagesController.php line 99 → Model->save(array)
[internal function] → PagesController->admin_add()
CORE/Cake/Controller/Controller.php line 490 → ReflectionMethod->invokeArgs(PagesController, array)
CORE/Cake/Routing/Dispatcher.php line 193 → Controller->invokeAction(CakeRequest)
CORE/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke(PagesController, CakeRequest)
APP/webroot/index.php line 118 → Dispatcher->dispatch(CakeRequest, CakeResponse)

**Comment by MichaelHoughton** [comment]
Hi @flik - does this happen every time, or only sometimes?

What type of database are you using?

**Comment by flik** [comment]
I am using ubuntu and created a database with phpmyadmin and then I imported the sql schema provided by you. 

This error was come on my first insertion then I did not try further.

**Comment by MichaelHoughton** [comment]
Hi There.  Would you mind sharing your PHP and Mysql version?  I was unable to create the error at my end.

**Comment by flik** [comment]
OS: ubunutu 14
PHP 5.5.21-1+deb.sury.org~precise+2 (cli) (built: Jan 26 2015 20:02:58)
mysql  Ver 14.14 Distrib 5.5.41, for debian-linux-gnu (i686) using readline 6.2

**Comment by MichaelHoughton** [comment]
Good news!  I have reproduced the bug - I will fix this tonight!

**Comment by brandonjjon** [comment]
I have also reproduced this! Thanks @MichaelHoughton

**Comment by MichaelHoughton** [comment]
Hi @flik and @brandonjjon - this is fixed.  It was an issue with the original SQL which is used when Coderity is installed.

@flik - if you empty your pages table, the dump this SQL, Coderity will then work successfully:

INSERT INTO `pages` (`id`, `parent_id`, `lft`, `rght`, `name`, `sub_title`, `meta_title`, `meta_description`, `meta_keywords`, `content`, `slug`, `route`, `post_route`, `view`, `class`, `top_show`, `top_order`, `bottom_show`, `bottom_order`, `new_window`, `element`, `created`, `modified`) VALUES
(1, NULL, 1, 2, 'Home', NULL, 'Home', '', '', '<p>Coming Soon</p>\r\n', 'home', '/', '', '', '', 1, 0, 0, NULL, 0, 0, NULL, NULL);

Also note, I updated the installation details yesterday, so if you want to use Coderity and make it your own, but also receive future updates, you can with this method:

http://www.coderity.com/download
